### ISSUE TITLE
running tfe provider remotely fails to create variables

### ISSUE THREAD

**Issue by jdtommy** [terraform-providers/terraform-provider-tfe#128] opened 2020-02-12 16:11 UTC
I am trying to have a tf file that manages the remote variables of our workspaces. When I run this example tf file locally it works fine, if I try and run it remotely it failes with:
`Error: Error creating terraform variable workspace: resource not found`

here is the tf info

```
provider "tfe" {
  hostname = "app.terraform.io"
}

terraform {
  backend "remote" {
    hostname = "app.terraform.io"
    organization = "org"
    workspaces {
      name = "app-terraform"
    }
  }
}

locals {
  workspaces = ["app-dev-useast1", "app-dev-uswest2", "app-int-uswest2"]
}

resource "tfe_workspace" "workspaces" {
  for_each = toset(local.workspaces)

  name = each.value
  organization = "org"
  file_triggers_enabled = false
  queue_all_runs = false

}

resource "tfe_variable" "workspace" {
  for_each = tfe_workspace.workspaces

  category = "terraform"
  key = "workspace"
  value = each.value.name
  workspace_id = each.value.id
}

output "test" {
  value = tfe_workspace.workspaces
}

**Comment by unknownterritory** [comment] 2020-03-31 19:21
@jdtommy , this is actually a duplicate of [CLI config not working for tfe provider #102](https://github.com/terraform-providers/terraform-provider-tfe/issues/102). You'll find what I hope to be a temporary workaround in [this comment](https://github.com/terraform-providers/terraform-provider-tfe/issues/102#issuecomment-553927663).

**Comment by lafentres** [comment] 2020-06-17 20:31
Closing as a duplicate of #102

**Closed by lafentres** 2020-06-17 20:31 UTC
